### Return all users
http://localhost:3005/users

### Find a user based of their id
http://localhost:3005/users/1

### Create a user
POST http://localhost:3005/users
Content-Type: application/json

{
    "username": "colin",
    "bio": "this isnt my real name"
}

### Update a user
PUT http://localhost:3005/users/1
Content-Type: application/json

{
    "username": "coast",
    "bio": "this isnt it either"
}

### Delete a user
DELETE http://localhost:3005/users/1

